### ISSUE TITLE
Project needs a README

### ISSUE THREAD

**Issue by avanwyk** [D3v01dZA/simplefinance#1]
Please add a README to the project so I can install it to simply manage my finances.

**Comment by D3v01dZA** [comment]
Thanks Andrich I added it

https://github.com/D3v01dZA/simplefinance/commit/3a77860bb5d8e3e3bb32ee3da10b255d56208c09

**Comment by avanwyk** [comment]
Wow, really quick turnaround on this issue.

Thanks 🎉
